baseURL = "https://til.12bit.vn"
languageCode = "vi-vn"
title = "Today I Learned"
theme = "til"
enableGitInfo = true
disqusShortname = "shortname"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-124810610-2"
uglyURLs=true
paginate=50


[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "content", "summary", "date", "publishdate", "permalink"]
params = ["tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/pages/about.html"

  [[menu.main]]
    identifier = "github"
    name = "Github"
    title = "Github"
    url = "https://github.com/12bitvn"

[params]
  description = "Little things learned everyday"
  author = "12bit.vn"

  [params.cta]
    name = "Add TIL"
    url = "/pages/contribute.html"

  [[params.social]]
      url = "https://github.com/12bitvn"
      fa_icon = "fa-github"

  [[params.social]]
      url = "https://12bit.vn"
      fa_icon = "fa-globe"

[blackfriday]
  hrefTargetBlank = true
