baseURL = "https://tils.netlify.com"
languageCode = "vi-vn"
title = "Today I Learned"
theme = "minitil"
enableGitInfo = true
disqusShortname = "shortname"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-124810610-2"
uglyURLs=true
paginate=20

[params]
  description = "Little things learned everyday"
  author = "12bit.vn"

[params.cta]
  name = "Add TIL"
  url = "/pages/contribute.html"

[[params.menu]]
  name = "Home"
  url = "/"

[[params.menu]]
  name = "About"
  url = "/pages/about.html"

[[params.social]]
    url = "https://github.com/12bitvn"
    fa_icon = "fa-github"

[[params.social]]
    url = "https://12bit.vn"
    fa_icon = "fa-globe"

[blackfriday]
  hrefTargetBlank = true